args: args.yaml
augmentation: trans01
class_names:
- disease_liver
- disease_liver_high
- disease_liver_low
- liver
- liver_high
- liver_low
- no_liver
dataset_conf: dataset4.yaml
loss_conf: CrossEntropyLoss
loss_param: {}
model_conf: resnext50_32x4d_1Line
model_param:
  pretrained: true
optimizer_conf: Adam
optimizer_param:
  lr: 0.0005
paramrequiresgrad: true
scheduler_conf: StepLR
scheduler_param:
  gamma: 0.1
  step_size: 7
seed: 123456789
